firefly:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  firefly/arm1_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: firefly/arm1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  firefly/arm2_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: firefly/arm2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  firefly/arm3_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: firefly/arm3_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
